### ISSUE TITLE
IMU and GPS hardware

### ISSUE THREAD

**Issue by gotros** [alex-makarov/robaka-ros#4]
Hi @alex-makarov,

what exact IMU and GPS hardware did you use? We try to rebuild the robot hardware identically. We follow the article under [https://medium.com/@alxm/converting-a-hoverboard-into-a-self-driving-mobile-robot-with-ros-d886c867e8a9](https://medium.com/@alxm/converting-a-hoverboard-into-a-self-driving-mobile-robot-with-ros-d886c867e8a9)

Great work and thanx in advance!

Greetz,
gotros

**Comment by alex-makarov** [comment]
Hey,

I'm using rather old [BT-818XT](http://www.qstarz.com/Products/GPS%20Products/BT-Q818-F.htm), but just because I had it already. You can use any GPS receiver which produces NMEA sentences with ROS, I believe.
IMU is from Adafruit - [this one](https://www.adafruit.com/product/1714)

FYI, I'm currently trying to make the semantic segmentation work for the costmap, so master branch can be a bit broken.

Happy to help.
